development:
  adapter: postgresql
  encoding: unicode
  database: ttt
  pool: 5
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: ttt-test
  pool: 5
  username: postgres
  password: admin
